# Generated by Django 5.1.6 on 2025-02-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_alter_habit_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_reminder",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Последнее напоминание в Телеграм"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="period",
            field=models.CharField(
                choices=[
                    ("every_hour", "Каждый час"),
                    ("twice_a_day", "Дважды в день"),
                    ("daily", "Ежедневно"),
                    ("once_every_three_days", "Раз в три дня"),
                    ("weekly", "Еженедельно"),
                ],
                max_length=21,
                verbose_name="Периодичность",
            ),
        ),
    ]
