# Generated by Django 5.1.6 on 2025-02-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_habit_last_reminder_alter_habit_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="period",
            field=models.CharField(
                choices=[
                    ("every_hour", "Каждый час"),
                    ("four_times_a_day", "Четыре раза в день"),
                    ("twice_a_day", "Дважды в день"),
                    ("daily", "Ежедневно"),
                    ("once_every_three_days", "Раз в три дня"),
                    ("weekly", "Еженедельно"),
                ],
                max_length=21,
                verbose_name="Периодичность",
            ),
        ),
    ]
